#  Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---

# Usage: set_kernel_params_facts.yml
warning_msg: "Warning: cmdline_value is empty for {{ item }}. No kernel command-line parameters will be set for this node."

# Usage: update_kernel_params.yml
provision_shared_library_path: "/opt/omnia/shared_libraries/provision"
servicetag_node_mapping_script: "{{ provision_shared_library_path }}/common/servicetag_node_mapping.py"
file_path_db: "{{ provision_shared_library_path }}/db_operations"
python_version: "python3.11"
invalid_host_msg: Invalid host in inventory file. Please update the inventory file with correct input and rerun the playbook."
