# Copyright 2025 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---

- name: Set default amdgpu status
  ansible.builtin.set_fact:
    amdgpu_config_status: false
    amdgpu_input_status: false

- name: Get amdgpu status
  ansible.builtin.set_fact:
    amdgpu_input_status: true
  loop: "{{ user_config.softwares | default([]) }}"
  when:
    - "'amdgpu' in item.name"
  loop_control:
    loop_var: item

- name: Set amdgpu_config_status
  when: amdgpu_input_status
  block:
    - name: Fetch amdgpu_version
      ansible.builtin.set_fact:
        amdgpu_version: "{{ user_config.softwares | selectattr('name', 'equalto', 'amdgpu') | map(attribute='version') | first }}"

    - name: Get amdgpu repository details from Pulp
      ansible.builtin.command: "{{ pulp_bin_path }} {{ os_package_map[provision_os] }} distribution list --name amdgpu_{{ amdgpu_version }}"
      delegate_to: localhost
      register: pulp_amdgpu_output
      changed_when: false

    - name: Parse amdgpu repository details
      ansible.builtin.set_fact:
        amdgpu_repo_list: "{{ pulp_amdgpu_output.stdout | from_json }}"
      when: pulp_amdgpu_output.stdout | from_json | length > 0

    - name: Set amdgpu_base_url and amdgpu_name if repository exists
      ansible.builtin.set_fact:
        amdgpu_base_url: "{{ amdgpu_repo_list[0]['base_url'] | default('') }}"
        amdgpu_name: "{{ amdgpu_repo_list[0]['name'] | default('') }}"
        amdgpu_config_status: true
      when: amdgpu_repo_list | length > 0

    - name: Warning - Please wait, This task will take few seconds
      ansible.builtin.pause:
        seconds: "{{ warning_wait_time }}"
        prompt: "{{ amdgpu_repo_warning_msg }}"
      when: pulp_amdgpu_output.stdout | length == 0

  rescue:
    - name: Warning - Please wait, This task will take few seconds
      ansible.builtin.pause:
        seconds: "{{ warning_wait_time }}"
        prompt: "{{ amdgpu_version_warning_msg }}"
